### ISSUE TITLE
Make the duration of the cover video shorter and darker

### ISSUE THREAD

**Issue by hwkeyser** [ShareVR/ShareVR-WebsiteDev#14]
> The video itself seems a little long to be on the header - would a visitor of the site stay in the header section of the website for 40 seconds?
> 
> The title and tagline of the headers also may block the content of the video, especially the part when the Facebook profile is shown. - Adam

**Comment by vivianzqq** [comment]
I agree we should probably make the cover video shorter. But it's kind of in the background, so I think probably that's not the priority now. For the height, it would be great if we can make it the same as the live site on wix, so that users can see the feature icons underneath as well.

**Comment by vivianzqq** [comment]
Thank you so much guys for helping out on this. I really appreciate it!!

**Comment by hwkeyser** [comment]
removing for now
