### ISSUE TITLE
Cover Video doesn't fill screen on Microsoft Edge browser

### ISSUE THREAD

**Issue by hwkeyser** [ShareVR/ShareVR-WebsiteDev#15]
Cover Video doesn't fill screen on my 4k monitor on Microsoft Edge, will test this on other browsers and other computers with lower res monitors later.

**Comment by adammy123** [comment]
Ah this was the issue i missed when i tried to remove the white gap in commit 23ec1cf9df3aed883d90ff6143712949075cfa1b.

**Comment by adammy123** [comment]
@hwkeyser is it okay now - can we close this issue?

**Comment by hwkeyser** [comment]
looks good to me.
