### ISSUE TITLE
Navbar font color

### ISSUE THREAD

**Issue by adammy123** [ShareVR/ShareVR-WebsiteDev#18]
As you scroll down the page, the navbar will change color, and the highlighted navbar words (home, documentation etc..) is also of the same color. This makes it a little bit unreadable, making the highlighted word almost invisible.

@vivianzqq would you want to take a look at this? it's just a color issue.. let me know if you don't understand what i'm saying!

**Comment by vivianzqq** [comment]
Thanks for bringing this up Adam. I realize this is an issue but haven't thought of a way to change it. Will work on it.

**Comment by hwkeyser** [comment]
I suggest we leave the navbar color for now and replace the remaining universal teal with a blue or something for the moment so that it more closely appeals to the placeholder Pryde logo

**Comment by hwkeyser** [comment]
no longer relevant
