### ISSUE TITLE
Cyan div with 4 feature circles is pushing over header

### ISSUE THREAD

**Issue by hwkeyser** [ShareVR/ShareVR-WebsiteDev#20]
The Cyan div (that has the 4 feature circles) will grow and cover up the header div (the header div has the cover video and buttons).

To recreate, open the landing page with your browser (where you can clearly read the Request a demo and learn more buttons), now squeeze the window to be thinner and you will see the problem.  

Instead of responding where the header text and buttons push the cyan div lower, the cyan div will stay locked to the bottom of the screen and will grow to cover up the buttons and text.

**Comment by adammy123** [comment]
@hwkeyser fixed - pinned the cyan div to the bottom of the header buttons instead when the screen size is smaller.

Lmk if there's still something wrong, if not feel free to close this.

**Comment by hwkeyser** [comment]
looks good
