### ISSUE TITLE
Unable to upload press photo

### ISSUE THREAD

**Issue by vivianzqq** [ShareVR/ShareVR-WebsiteDev#8]
The press photo, which is called "wildfirephoto.JPG" in the my local file in the img folder. But when I use git add * to add all the new files to the master repo, this photo file is not there. So the photo currently doesn't show on the test landing page.

**Comment by adammy123** [comment]
@vivianzqq can you manually upload it here? Anyway, i recommend using the GitHub Desktop App for mac, i find it easier to push the files by clicking a button rather than using command line.

**Comment by vivianzqq** [comment]
This is solved. It's because github is case sensitive, so I change the file name in the code and the photo shows up after that.
