### ISSUE TITLE
Unable to adjust styling of the send button on contact form 

### ISSUE THREAD

**Issue by vivianzqq** [ShareVR/ShareVR-WebsiteDev#9]
This appears on every page. I want to change the button color and the padding and make it look the same as the one on our current wix site. But the styling changes I made in the css code do not reflect in the related html code. 

Now the button size, button color and button padding all need to change, and I just cannot change any of them. 

This is the format we have on our current wix site:
    border: none;
    cursor: pointer;
    background-color: rgba(0, 0, 0, 1); 
    color: #FFFFFE;
    width: 100%;
    min-height: 45px;
    display: block;
    margin-bottom: 15px;
    font: normal normal normal 17px/1.4em raleway,sans-serif; (I have the right font in place now. No need to change this)
    padding: 5px;

We don't need to use the same code, but we need to adjust the button color, button size and button padding to make it look the same as the one on the live site.

**Comment by chenchen2015** [comment]
@adammy123 @hwkeyser can anyone help her with this? If you want to help, please simply assign yourself

**Comment by adammy123** [comment]
I'll look at this

**Comment by adammy123** [comment]
@vivianzqq if it looks ok, feel free to close the issue!

**Comment by vivianzqq** [comment]
Thanks Adam!!! It looks perfect. I'll close this one.
